-- 코드를 입력하세요
SELECT ROUND(DATE_FORMAT(A.START_DATE, '%m')) AS MONTH, A.CAR_ID, COUNT(A.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN (SELECT CAR_ID, COUNT(*) as COUNT
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE LEFT(START_DATE, 7) BETWEEN '2022-08' AND '2022-10'
      GROUP BY CAR_ID) B
ON A.CAR_ID = B.CAR_ID
WHERE B.COUNT > 4 AND LEFT(A.START_DATE, 7) BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;