SELECT ID, CASE WHEN RANKING = 1 THEN 'CRITICAL'
               WHEN RANKING = 2 THEN 'HIGH'
               WHEN RANKING = 3 THEN 'MEDIUM'
               ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING
      FROM ECOLI_DATA) A
ORDER BY ID
                        
# SELECT ID, (CASE 
#             WHEN CLASS = 1 THEN 'CRITICAL'
#             WHEN CLASS = 2 THEN 'HIGH'
#             WHEN CLASS = 3 THEN 'MEDIUM'
#             WHEN CLASS = 4 THEN 'LOW'
#             END) AS COLONY_NAME
# FROM (
#     SELECT * , NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS CLASS
#     FROM ECOLI_DATA) AS TEMP
# ORDER BY 1 DESC