SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS A JOIN ANIMAL_INS B USING(ANIMAL_ID)
WHERE (SEX_UPON_OUTCOME LIKE 'SPAYED%' OR SEX_UPON_OUTCOME LIKE 'NEUTERED%') AND SEX_UPON_INTAKE LIKE 'INTACT%'
ORDER BY ANIMAL_ID