-- 코드를 입력하세요

SELECT A.CAR_ID, CASE WHEN B.START_DATE IS NULL THEN '대여 가능' ELSE '대여중' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT OUTER JOIN (SELECT CAR_ID, START_DATE, END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE 
) B
USING (CAR_ID)
GROUP BY CAR_ID
ORDER BY CAR_ID DESC