SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A JOIN PATIENT B USING (PT_NO) JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE A.MCDP_CD = 'CS' AND DATE(APNT_YMD) = '2022-04-13' AND APNT_CNCL_YMD IS NULL
ORDER BY APNT_YMD