# SELECT MEMBER_ID
# FROM MEMBER_PROFILE A JOIN REST_REVIEW B USING (MEMBER_ID)
# GROUP BY MEMBER_ID
# ORDER BY COUNT(*) DESC
# LIMIT 1

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A JOIN MEMBER_PROFILE B USING (MEMBER_ID)
WHERE MEMBER_ID = (SELECT MEMBER_ID
                   FROM MEMBER_PROFILE A JOIN REST_REVIEW B USING (MEMBER_ID)
                   GROUP BY MEMBER_ID
                   ORDER BY COUNT(*) DESC
                   LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT