-- 코드를 작성해주세요
SELECT B.ID, B.GENOTYPE, A.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA A JOIN (SELECT ID, PARENT_ID, GENOTYPE
                      FROM ECOLI_DATA) B ON A.ID = B.PARENT_ID
WHERE !((B.GENOTYPE - A.GENOTYPE) & A.GENOTYPE)

# 1101
#- 101
#  100