# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE '2022-08-01' <= LEFT(START_DATE, 10) AND LEFT(START_DATE, 10) < '2022-11-01'
# GROUP BY CAR_ID
# HAVING COUNT(*) > 4

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
                GROUP BY CAR_ID
                HAVING COUNT(*) > 4 AND (START_DATE BETWEEN '2022-08-01' AND '2022-10-31'))
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC