# SELECT ID, C.FISH_NAME, A.LENGTH
# FROM FISH_INFO A JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS ML
#                        FROM FISH_INFO
#                        GROUP BY FISH_TYPE) B ON A.FISH_TYPE = B.FISH_TYPE JOIN (SELECT FISH_TYPE, FISH_NAME
#                                                                                 FROM FISH_NAME_INFO) C ON B.FISH_TYPE = C.FISH_TYPE
# WHERE LENGTH = ML
# ORDER BY ID

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B USING(FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH)
                              FROM FISH_INFO
                              GROUP BY FISH_TYPE)
ORDER BY ID