-- 코드를 입력하세요
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A
RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
USING (CAR_ID)
WHERE A.CAR_TYPE = '세단' AND B.START_DATE LIKE '2022-10-%'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC