# SELECT BOOK_ID, SUM(SALES) AS SALES
# FROM BOOK_SALES
# GROUP BY BOOK_ID

# SELECT * FROM BOOK



SELECT A.CATEGORY, SUM(S) AS TOTAL_SALES
FROM BOOK A JOIN (SELECT BOOK_ID, SUM(SALES) AS S
                  FROM BOOK_SALES
                  WHERE SALES_DATE LIKE '2022-01%'
                  GROUP BY BOOK_ID) B ON A.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY

# SELECT BOOK_ID, SUM(SALES) AS S
# FROM BOOK_SALES
# GROUP BY BOOK_ID